ExploreCalifornia/Models/Post.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ExploreCalifornia.Models
{
    public class Post
    {
        [Key]
        public long Id { get; set; }

        [Display(Name ="Post Tilte")]
        [MaxLength(100)]
        [Required]        
        public string Title { get; set; }
        
        [Required]
        [Display(Name = "Author's Name")]
        public string Author { get; set; }

        [MaxLength(500)]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }

        [DataType(DataType.Date)]
        public DateTime PostedOn { get; set; } = DateTime.Now;
    }
}

ExploreCalifornia/ViewModels/PostViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace ExploreCalifornia.ViewModels
{
    public class PostViewModel
    {
        [Key]
        public long Id { get; set; }

        [Display(Name = "Post Tilte")]
        [MaxLength(100)]
        [Required]
        public string Title { get; set; }

        [MaxLength(500)]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [Required]
        [Display(Name = "Author's Name")]
        public string AuthorName { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
    }
}

ExploreCalifornia/Controllers/BlogController.cs
using ExploreCalifornia.DAL;
using ExploreCalifornia.MiddleWares;
using ExploreCalifornia.Models;
using ExploreCalifornia.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Diagnostics;
using System.Linq;

namespace ExploreCalifornia.Controllers
{

    [Route("blog")]
    //[MiddlewareFilter(typeof(CompressionMiddlerWare))]
    public class BlogController : Controller
    {
        private readonly BlogDbContext _dbContext;
        private readonly IOptions<ConnectionStrings> _connectionStrings;

        public BlogController(BlogDbContext blogDataContext , IOptions<ConnectionStrings> connectionStrings)
        {
            _dbContext = blogDataContext;
            _connectionStrings = connectionStrings;
        }
        [Route("")]
        public IActionResult Index(int page = 0)
        {
            var pageSize = 2d;
            var totalPosts = _dbContext.Posts.Count();
            var totalPages = Math.Ceiling(totalPosts / pageSize);
            var previousePage = page - 1;
            var nextPage = page + 1;

            ViewBag.PrevioisePage = previousePage;
            ViewBag.HasPrevioisePage = previousePage>=0;

            ViewBag.NextPage = nextPage;
            ViewBag.HasNextPage = nextPage < totalPages;

            var posts = _dbContext.Posts
                .OrderByDescending(p=>p.PostedOn).Skip((int)pageSize * page)
                .Take((int)pageSize).Select(p => p.ToViewModel()).ToList();

            if (IsAjaxRequest())
            {
                return PartialView(posts);
            }

            return View(posts);
        }


        [Authorize]
        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        [Route("{year:int}/{month:int}/{key}")]
        public IActionResult Post(int year, int month, int key)
        {
            var post = _dbContext.Posts.FirstOrDefault(x => x.Id == key);            
            return View(post.ToViewModel());
        }

        [Authorize]
        [HttpPost]
        [Route("create")]
        public IActionResult Create([FromForm] PostViewModel postData)
        {
            if (!ModelState.IsValid)
                return View(postData);

            try
            {                
                var post = postData.ToPostEntity();              
                _dbContext.Posts.Add(post);
                _dbContext.SaveChanges();

                return RedirectToAction("Post", new { year = post.PostedOn.Year, month = post.PostedOn.Month, key = post.Id });
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                throw;
            }
        }

        private bool IsAjaxRequest()
        {
            return Request.Headers["X-Requested-With"] == "XMLHttpRequest";
        }
    }

    public static class PostExtensions
    {
        public static PostViewModel ToViewModel(this Post post)
        {
            return new PostViewModel
            {
                AuthorName = post.Author,
                Content = post.Body,
                Title = post.Title,
                Date = post.PostedOn,
                Id = post.Id
            };
        }

        public static Post ToPostEntity(this PostViewModel post)
        {
            var postDateParsed = DateTime.TryParse(post.Date.ToString(), out DateTime postDate);
            return new Post
            {
                Author = post.AuthorName ,
                Body = post.Content,
                Title = post.Title,
                PostedOn = postDateParsed ? postDate.Date : DateTime.UtcNow,
                Id = post.Id
            };
        }
    }
}

ExploreCalifornia/ViewComponents/ExploreCaliforniaLabelViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ExploreCalifornia.ViewComponents
{
    public class ExploreCaliforniaLabelViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(string title)
        {
            return Task.FromResult<IViewComponentResult>(View("Default", title));
        }
    }
}

ExploreCalifornia/ViewComponents/MontlhySpecialsViewComponent.cs
using ExploreCalifornia.DAL;
using Microsoft.AspNetCore.Mvc;

namespace ExploreCalifornia.ViewComponents
{
    
    public class MontlhySpecialsViewComponent : ViewComponent
    {
        private readonly BlogDbContext _dbContext;

        public MontlhySpecialsViewComponent(BlogDbContext blogDataContext)
        {
            _dbContext = blogDataContext;
        }
        
        public IViewComponentResult Invoke()
        {           
            return View(_dbContext.MonthlySpecials);
        }
    }
}

ExploreCalifornia/Views/Shared/_Layout.cshtml
@addTagHelper  *, ExploreCalifornia
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var headerSectionName = "header";
}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Welcome to Explore California</title>
    <meta name="description" content="A lynda.com example of HTML5 and CSS3">
    <meta name="keywords" content="html5, css3, lynda, local storage, canvas, forms, semantics, web apps">
    <!--make sure mobile devices display the page at the proper scale	-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <environment names="Development">
       @* <link href="/css/main.css" rel="stylesheet" type="text/css" media="screen, projection" />*@
        <link rel="stylesheet" href="/css/bundle.css" />
        <script src="~/js/jquery/jquery.min.js"></script>
        <script src="~/js/site.js"></script>
    </environment>

</head>
<body id="home" class="no-js">
    <div id="wrapper">
        <header id="mainHeader">
            <a href="/" title="home" class="logo">
                <!-- I need this div because IE is an affront to mankind-->
                <div>
                    <h1>Explore California</h1>
                </div>
            </a>
            <nav id="siteNav">
                <h1>Where do you want to go?</h1>
                <ul>
                    <li>
                        <a href="/tours.htm" title="Our tours">Tours <br /><span class="tagline">follow our bliss</span></a>
                        <ul>
                            <li><a href="/tours.htm" title="Our tours">All Tours</a></li>
                            <li><a href="/tours.htm" title="find tours">Tours by Activity</a></li>
                            <li><a href="/tours.htm" title="find tours">Tours by Region</a></li>
                            <li><a href="/tours.htm" title="find tours">Tour Finder</a></li>
                             <li><a asp-area="MyFeature" asp-page="/Page1"  title="find tours">Page1</a></li>
                            <li>
                                <a href="@Url.Action("RCL","Account")" title="Read our blog!">RCL</a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="mission.htm" title="What we believe">Mission <br /><span class="tagline">what makes us different?</span></a></li>
                    <li>
                        <a href="resources.htm" title="planning resources">Resources <br /><span class="tagline">plan your trip</span></a>
                        <ul>
                            <li><a href="resources/faq.htm" title="Got questions?">Tour FAQs</a></li>
                            <li><a href="resources/additional_resources.htm" title="additional resources">Tour Information</a></li>
                            <li><a href="resources/terms.htm" title="terms and conditions">Site Terms</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="explorers.htm" title="Our community">Explorers <br /><span class="tagline">join our community</span></a>
                        <ul>
                            <li><a href="explorers/join.htm" title="join our community">Join the Explorers</a></li>
                            <li>
                                <a href="@Url.Action("Index","Blog")" title="Read our blog!">Read our blog</a>
                            </li>
                            <li><a href="explorers/gallery.htm" title="contributor photos">Tour Photos</a></li>
                            <li><a href="_video/EC_podcast_full version.mov" title="check out our podcast">Video podcast</a></li>
                        </ul>
                    </li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <form asp-action="Logout" asp-controller="Account" method="post">
                                <button type="submit">Logout ( @User.Identity.Name)</button>
                            </form>
                        }
                        else
                        {
                            <a href="@Url.Action("Login","Account")" class="last">Login</a>
                        }
                    </li>
                </ul>
            </nav>
        </header>
        <section id="actionCall">
            @if (IsSectionDefined(headerSectionName))
            {
                @RenderSection(headerSectionName)
            }
            else
            {
                <h1>Explore our world your way</h1>
            }
        </section>
        <div id="contentWrapper">
            <section id="mainContent">
                @RenderBody()
            </section>
            <aside id="secondaryContent">
                <div id="specials" class="callOut">
                    @await Component.InvokeAsync("ExploreCaliforniaLabel", new {title= "reza"})
                    <vc:montlhy-specials />
                </div>
                <div id="trivia" class="callOut">
                    <h1>Did You Know?</h1>
                    <p>California produces over 17 million gallons of wine each year!</p>
                </div>
            </aside>
        </div>
        <footer id="pageFooter">
            <section id="quickLinks">
                <h1>Quick Nav</h1>
                <ul id="quickNav">
                    <li><a href="/" title="Our home page">Home</a></li>
                    <li><a href="/tours.htm" title="Explore our tours">Tours</a></li>
                    <li><a href="mission.htm" title="What we think">Mission</a></li>
                    <li><a href="resources.htm" title="Guidance and planning">Resources</a></li>
                    <li><a href="explorers.htm" title="Join our community">Explorers</a></li>
                    <li><a href="contact.htm" title="Contact and support">Contact</a></li>
                </ul>
            </section>
            <section id="footerResources">
                <h1>Resources</h1>
                <ul id="quickNav">
                    <li><a href="resources/faq.htm" title="Our home page">FAQ</a></li>
                    <li><a href="support.htm" title="Need help?">Support</a></li>
                    <li><a href="resources/legal.htm" title="The fine print">Legal</a></li>
                    <li><a href="login.htm">Login</a></li>
                </ul>
            </section>
            <section id="companyInfo">
                <h1>Contact</h1>
                <h2>Explore California</h2>
                <p>
                    5605 Nota Street<br />
                    Ventura, CA 93003
                </p>
                <p>866.555.4310<br />866.555.4315 <em>(24 hour support)</em></p>
            </section>
        </footer>
    </div>
 @* <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="~/lib/js/bundle.js" ></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ExploreCalifornia/Views/Shared/_Post.cshtml
@inject ExploreCalifornia.Models.FormattingService Format
@model ExploreCalifornia.ViewModels.PostViewModel

<article class="blog-post">
    <h1><a href="@Url.Action("Post","Blog",new {year = Model.Date.Year  , month = Model.Date.Month , key = Model.Id})">@Model.Title</a></h1>
    <div class="details">
        Posted <span class="blog-date">@Format.AsReadableDate(Model.Date)</span> by <span>@Model.AuthorName</span>
    </div>
    <div class="content">
        @Model.Content
    </div>
</article>